### ISSUE TITLE
Failed to connect to proxy.truc.fr port 8080: Connection timed out

### ISSUE THREAD

**Issue by VirginieBfd** [olivierhagolle/peps_download#29]
Bonjour Olivier, 

When trying to download a tile, I encountered the following error: 
`Failed to connect to proxy.truc.fr port 8080: Connection timed out`

```
python ./peps_download.py  -c S2 -l 'Toulouse' -a peps.txt -d 2015-12-15 -f 2015-12-01
curl -k -o search.json https://peps.cnes.fr/resto/api/collections/S2/search.json?q=Toulouse\&startDate=2015-12-15\&completionDate=2015-12-01\&maxRecords=500
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:10 --:--:--     0curl: (7) Failed to connect to proxy.truc.fr port 8080: Connection timed out
Traceback (most recent call last):
  File "./peps_download.py", line 307, in <module>
    prod, download_dict, storage_dict, size_dict = parse_catalog(options.search_json_file)
  File "./peps_download.py", line 47, in parse_catalog
    with open(search_json_file) as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'search.json'
```

Do you know how to avoid this problem? Do you have a tutorial to connect through a proxy?

Best regards,

Virginie

**Comment by VirginieBfd** [comment]
Sorted, local config was interfering!

**Comment by olivierhagolle** [comment]
Good to know.
